Message re-assembly
Apollon77/matter.js pull request #4
Opened 2023-06-30 19:56 UTC by mahimamandhanaa

2023-07-03 19:51 UTC, Apollon77 requested changes

2023-07-03 19:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private msgLength: number | undefined = 0;
maybe rename into "currentSegmentedMsgLength" or such so that it is more clean what it is about. same for next one

2023-07-03 19:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        // BTP_CONN_RSP_TIMEOUT - 5sec
if you like define as constant outside of the class and maybe do in ms for easier usage

2023-07-03 19:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                this.msgLength = messageLength;
I would add a check here that there is norhing "in flight" from before and at leats log a warning that data is discarded

2023-07-03 19:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private msgLength: number | undefined = 0;
And maybe really initialize with "undefined" (or no initialize this and next to see that no "isBeginning" came in) . the = 0 will initialize to 0

2023-07-03 19:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (segmentPayload == undefined) {
Thats not needingly true ... there can be ack only packets .... also in our case we might always have a payload, but length 0. Maybe skip this specific check for now

2023-07-03 19:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                if (this.msgLength == undefined) {
Please always use typesafe comparisms ... so ===

... aaand basically can never be the case because it is always a number ... if you like to use this as check variable then you need to settít to undefined after isEndingSegment is processed

2023-07-03 19:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    throw new Error(`BTP packet payload length does not match message length: ${this.payload.length} !== ${this.msgLength}`);
I would also disconnect here

2023-07-03 19:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    throw new Error("BTP packet sequence numbers are incorrect");
Please add info to exception like both numbers that are not matched ... else you will later search forever for reasons :-) same for the other throws above please

2023-07-03 19:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                this.lastIncomingSequenceNumber = sequenceNumber;
This will not work because I used this variable as" send this as ack on next sent package" ... needs to be adjusted like 4.17.3.7 describes

2023-07-03 19:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                this.lastIncomingSequenceNumber = sequenceNumber;
One pragmatic alternative to try would be to send one "ack only" package back for each incoming message which has no "isEndingSegment" set (because that one from the ending one is sent with the response then)

2023-07-03 22:43 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (segmentPayload == undefined) {
this check is required because we have defined segmentPayload as an optional field. Should I remove the segmentPayload as optional field in `BtpCodec` as it can just be 0 if the payload is not empty?

2023-07-03 22:45 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                if (this.msgLength == undefined) {
here `currentSegmentedMsgLength` is also an optional field hence I added the condition. Updated, let me know if you want to keep it as a non-optional field

2023-07-03 22:45 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    throw new Error(`BTP packet payload length does not match message length: ${this.payload.length} !== ${this.msgLength}`);
added

2023-07-03 22:52 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        // BTP_CONN_RSP_TIMEOUT - 5sec
just added  it as a comment for now, deleted

2023-07-03 22:52 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private msgLength: number | undefined = 0;
Updated

2023-07-03 22:54 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    throw new Error("BTP packet sequence numbers are incorrect");
done

2023-07-04 06:25 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (segmentPayload == undefined) {
okj yes ... I mixed up things

2023-07-04 06:27 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private currentSegmentedMsgLength: number | undefined = undefined;
nit, the = undefiend is notneeded because default value in that case

2023-07-04 06:30 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                this.currentSegmentedMsgLength = 0;
i think this needs to be removed (that second line setting it to 0)

2023-07-04 07:38 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private currentSegmentedMsgLength: number | undefined = undefined;
removed

2023-07-04 07:38 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                this.currentSegmentedMsgLength = 0;
yup, I removed it and changed the logic

2023-07-05 07:40 UTC, Apollon77 requested changes

2023-07-05 07:40 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            isBeginningSegment: false,
for a new package isBeginning of the initial packet is always true (else also your header length calculation below is wrong, so I would set that here already and remove below

2023-07-05 07:40 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    messageLength: header.isBeginningSegment ? data.length : undefined,
also here, you know it is always true ... soooo no need for the check

2023-07-05 07:40 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        if (data.length < this.attMtu - expectedBtpHeaderLength) {
formally <= as comparism ?

2023-07-05 07:40 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                const segment = data.slice(startIndex, Math.min(startIndex + this.attMtu - expectedBtpHeaderLength, data.length));
fomally expected btp header length is not static ... because messagelength is only in the first package ... after that header is 2 bytes smaller

2023-07-05 07:40 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                this.segmentPayloads.push(segment);
why this is a instance variable? should be a local one ... (also because you created a great issue ... you add stuff here the you process it but you never clear this.segmentPayloads, so next package would contain stuff from before ... This do not happen when it is a local variable ... just this.btpPackets needs to be instance variable, right

2023-07-05 07:40 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            this.segmentPayloads.forEach((_value, index, array) => {
First of all I would merge that loop with the above while. You know all cases there too startIndex === 0 for first and startIndex > data.length for last, all others in between

2023-07-05 07:40 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    header,
this might not work because header is an object ... so you asign the reference here and in fact each change will be for all packages. I would simply create a new header onject for each iteration

2023-07-05 07:40 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                        messageLength: header.isBeginningSegment ? data.length : undefined,
"data" here is the incoming data and not the segment value ...... ;-)) This will not work at all

2023-07-05 07:40 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                btpPayload = BtpCodec.encodeBtpPacket({
As written in discord. Please do notpush the encoded packets but the "Objects" because the sending loop might need to adjust at least the ackNumber dynamically

2023-07-05 07:40 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        this.btpPackets.forEach(async (btpPayload) => {
Ideally create an own "sendQueuesBtpFrames" method and just trigger that from here when this.btpPackets.length === 1 ... and this method then also takes care of the client window limit

if you do it that way you could send out two responses in parallel which is forbidden.

2023-07-05 17:16 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            this.segmentPayloads.forEach((_value, index, array) => {
I cannot add the `startIndex > data.length` condition inside the loop, and now I will not be needing `startIndex === 0` condition as well because we have initialized header with `isBeginningSegment = true`.

2023-07-05 17:24 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            this.segmentPayloads.forEach((_value, index, array) => {
I do not get what you mean?

2023-07-05 18:26 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            isBeginningSegment: false,
yeah you are right, set `isBeginningSegment: true`

2023-07-05 18:27 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                const segment = data.slice(startIndex, Math.min(startIndex + this.attMtu - expectedBtpHeaderLength, data.length));
updated

2023-07-05 18:27 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                this.segmentPayloads.push(segment);
correct, my mistake.
Updated

2023-07-05 18:27 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            this.segmentPayloads.forEach((_value, index, array) => {
Updated as discussed

2023-07-05 18:28 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                btpPayload = BtpCodec.encodeBtpPacket({
pushed objects

2023-07-05 18:28 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    header,
created a new header

2023-07-05 18:28 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                        messageLength: header.isBeginningSegment ? data.length : undefined,
replaced data with `segment`

2023-07-05 18:29 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        this.btpPackets.forEach(async (btpPayload) => {
Updated the method with the condition, working on `sendQueuesBtpFrames`

2023-07-05 22:14 UTC, Apollon77 requested changes

2023-07-05 22:14 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                segmentPayloads.push(segment);
No longer needed or?

2023-07-05 22:14 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    packetHeader = {
Ok inside the loop with a block scoped variable you can modify the header simply. So no need to overwrite

2023-07-05 22:14 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    this.sendQueuesBtpFrames(this.btpPackets);
I would love that to outside of while loop

2023-07-05 22:14 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        if (this.sequenceNumber - this.lastIncomingSequenceNumber > this.clientWindowSize) {
This is wrong. You mix incoming and outgoing sequence numbers.

2023-07-05 22:14 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                btpPacket.payload.ackNumber = this.serverWindow.shift();
Check specs. I understand that in a way that you only need to ack the highest number. Not needed all.

2023-07-05 22:14 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            logger.debug(`Sending Matter Message response: ${packet.toHex()}`);
Break. Else you miss to set sendInprogress to false

2023-07-05 23:14 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                segmentPayloads.push(segment);
removed

2023-07-05 23:15 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    packetHeader = {
okay, updated

2023-07-05 23:15 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    this.sendQueuesBtpFrames(this.btpPackets);
so are we waiting for all the msgs to be pushed in an array first and then try sending them one by one?

2023-07-05 23:16 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        if (this.sequenceNumber - this.lastIncomingSequenceNumber > this.clientWindowSize) {
yess, have changed

2023-07-05 23:16 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                btpPacket.payload.ackNumber = this.serverWindow.shift();
updated accordingly

2023-07-05 23:16 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            logger.debug(`Sending Matter Message response: ${packet.toHex()}`);
added break

2023-07-06 06:50 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    this.sendQueuesBtpFrames(this.btpPackets);
it does not make a real difference, but make it once after loop is better code (becasue in fact any second call  does nothing other then return in the function

2023-07-06 07:23 UTC, Apollon77 requested changes

2023-07-06 07:23 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        let btpPayload: BtpPacket;
no need to have that variable outside the look. better use local block scoped variables

2023-07-06 07:23 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    packetHeader.isEndingSegment = false;
last package needs ending = true

2023-07-06 07:23 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    this.btpPackets.push(btpPayload);
You kind of duplicating code her e... just because of the break ... I would remove this here and do another "if isEnding -> break" at the end of the while code

2023-07-06 07:23 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        await this.sendQueuesBtpFrames(this.btpPackets);
but do not pass "this.btpPackets" but let the sendQueue function work itself over this.btpPackets

2023-07-06 07:23 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    async sendQueuesBtpFrames(packets: Array<BtpPacket>) {
pakets -> this.btpPackets ... no need to pass here

2023-07-06 07:23 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (this.lastIncomingSequenceNumber !== undefined) {
you also need to remember which incoming AckNumber you acked already because resending the same number makes no sense. So maybe do a new this.lastAckedIncomigSequenceNumber variable and set the number you ack here ... and if it is the same as lastIncomingSequence number then nothing needed to be acked.

Or we now rename to names with "ClientSequenceNumber" for all incoming and "Server" for all outgoing such data.

2023-07-06 07:23 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                const timeout = setTimeout(() => {
This do not work here that way because writeBleCallback is just writing out data ... is tells nothing if they got acked (and ack in this case means really receiving an message with an ack in!!

I would really implement it as staed in the specs.

Create two timers. one for "you sent a package and expect ack to be received" and one for "WE got a package and need to send an ack".

Additionally Timers are abstracted away in our lib here, but thats also good because easier.

I would define the two timer as instance variables like

needToSendAckTimer = Time.getTimer(timeinMs, () => callback); // will be started later

You can then do needToSendAckTimer.start() to start the time and ".stop()" to stop it. You can also use isRunning property to see if it is already running.

This is needed because "setTimeout is a platform specific functionality that works different eg in browsers butmatter.js is platform agnostic.

And then you add the relevant functions in the receiving and sending methods to start/stop the timers as needed and as in specs.

2023-07-06 07:23 UTC, Apollon77 commented on packages/matter.js/test/ble/BtpSessionHandlerTest.ts
> +            void btpSessionHandler?.handleIncomingBleData(matterMessage);
you should maybe also await here?

2023-07-06 17:18 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    console.warn("Inflight data is discarded");
yes, we need to. Cleared the `currentSegmentedPayload`

2023-07-06 17:49 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (this.lastIncomingSequenceNumber !== undefined) {
Added the logic of checking which ack number we are planning to send and if it is already sent, do not send it

2023-07-07 08:51 UTC, Apollon77 requested changes

2023-07-07 08:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        let expectedBtpHeaderLength = 2 + (this.serverAckedSequenceNumber !== undefined ? 1 : 0) + (header.isBeginningSegment !== undefined ? 2 : 0);
Ok lets assume there is alwys an ack nunmber and remove that  here:

```suggestion
        let expectedBtpHeaderLength = 3 + (header.isBeginningSegment !== undefined ? 2 : 0);
```

2023-07-07 08:51 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                expectedBtpHeaderLength = 2 + (this.serverAckedSequenceNumber !== undefined ? 1 : 0);
here set directly to 3

2023-07-07 16:47 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        let expectedBtpHeaderLength = 2 + (this.serverAckedSequenceNumber !== undefined ? 1 : 0) + (header.isBeginningSegment !== undefined ? 2 : 0);
why are we assuming that we will always have the ack number?

2023-07-07 16:54 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        let expectedBtpHeaderLength = 2 + (this.serverAckedSequenceNumber !== undefined ? 1 : 0) + (header.isBeginningSegment !== undefined ? 2 : 0);
In this case it is simplification ... because we split the matter message into segments directly and sending later. so there COULD be an ack number (or not). In fact the only difference is that our segments are potentially (if we have no ack number) one byte smaller. But in fact checking at the timepoint of splitting if we "NOW have one ack number to send" is wrong because what if not?

So this is a pragmatic way with the risk of loosing one byte in segment size.

If you want to implement it formally right you need to move the whole packet generation into the "sendQueue" method and remember if you have started a packet already and such and just pushing the matter message into the queue.
Then you do that in that function exactly then when you sent out the packet and the n you know exactly IF you need to add an ack number or not. We culd also adjust it that way

2023-07-07 17:02 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        let expectedBtpHeaderLength = 2 + (this.serverAckedSequenceNumber !== undefined ? 1 : 0) + (header.isBeginningSegment !== undefined ? 2 : 0);
okay, so since we are adding the ackNumber later after splitting the data, we will need a buffer of 1 byte for the ackNumber.

2023-07-07 17:20 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    this.serverAckedSequenceNumber = ackNumber;
I have already added the check in `startBtpAckTimer` method. Should that logic be here?

2023-07-07 20:05 UTC, Apollon77 requested changes

2023-07-07 20:05 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        if (!this.btpAckTimer.isRunning) {
The methon only gets triggered when the timer triggered it .. and so it is always !isRunning because the timer expired ... sooooo this block makes no sense

2023-07-07 20:05 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            this.btpAckTimer.stop();
the disconnect and throew needs to go here!

Because when this timer triggered we were not receiving an ack to our latest message within the timeout time. this mens something is wrong when we miss an ack. so we cancel the connection, right?

2023-07-07 20:05 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        if (!this.btpSendAckTimer.isRunning) {
same here, is alwys "!isRunning" ... please remove

2023-07-07 20:05 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            this.btpSendAckTimer.stop();
why stop, it is already stopped because the methid here got triggered ... or do you wanted to start the btpAckTimer if not already running?

2023-07-10 17:04 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            this.btpSendAckTimer.stop();
Yes correct, I have to start the timer here because the empty payload also needs to be acked

2023-07-10 17:26 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (sequenceNumber <= this.serverAckedSequenceNumber) {
I meant `this.sequenceNumber` here

2023-07-10 18:02 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (sequenceNumber <= this.serverAckedSequenceNumber) {
removed this piece, as it is not needed because if there is no ackNumber received then we should not stop the timer.

2023-07-10 18:02 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        if (!this.btpAckTimer.isRunning) {
Removed

2023-07-10 18:02 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            this.btpAckTimer.stop();
added `!==` check

2023-07-10 19:07 UTC, swan-amazon commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    async sendQueuesBtpFrames() {
I don't like the statefulness of your class. It seems the only reason we have many of the `private class members` is so that you can avoid having parameters on your helper functions. You should be able to locally allocate your packet buffers when you are sending.

1. sendMatterMessage(message)
2. packets = encodeMessage(message)
3. sendPackets(packets)

or you could figure out a way to create a stream so that you yield packets from your function until the last one, and you stream the packet directly to the transport. Kind of like an iterator.

1. sendMatterMessage(message)
2. packetsSteam = encodeMessageStream(message)
3. sendPackets(packetsSteam)

2023-07-10 19:07 UTC, swan-amazon commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            }
Is this an error? It seems suspicious to me that you have two exit conditions from the loop, without different status codes. It should just be `while (!queue.empty()) { item = queue.pop(); handle(item); }`

2023-07-10 19:07 UTC, swan-amazon commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            await this.writeBleCallback(packet);
What is the contract for the function? Does it `resolve`, `reject`, or `throw`? Should we be checking the status?

2023-07-10 19:14 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +const BTP_ACK_TIMEOUT = 15000; // timer in ms before ack should be sent for a segment
I am following the variable names as defined in the matter spec.

2023-07-10 19:16 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
>              }
So currently we just support one version.
`4 — BTP as defined by Matter v1.0` - as mentioned in the matter spec

2023-07-10 19:19 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        this.btpAckTimer = Time.getTimer(BTP_ACK_TIMEOUT, () => this.btpAckTimoutTriggered());
IntelliJ error - `Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead`

2023-07-10 19:22 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
>              } = btpPacket;
I am not changing its structure nor correcting it, I am just defining objects so that I can use them to later for certain checks. These variables have already been created in `BtpCodec`

2023-07-10 19:33 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            await this.writeBleCallback(packet);
it resolves and rejects. The error part will be handled by the timer.

2023-07-10 19:37 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +const BTP_ACK_TIMEOUT = 15000; // timer in ms before ack should be sent for a segment
Yes, in this case we try to stay close to Matter spec where possible (even if this in this case is slightly inconsistent with normal practices ... But in this case it is still easy to find. @mahimamandhanaa  lets add _MS

2023-07-10 19:45 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
>          const header = {
Yeah, so the messages can be represented as the 

- Starting packet, ending packet, middle packet 

- So all the messages do not necessarily have an ack number. It wouldn't mean anything. It just sending the segmentPayload instead of the ackNumber

- the handshake payloads consists of opcodes (0x6c), whereas the other packet payloads do not contain opcode

2023-07-10 19:46 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        let expectedBtpHeaderLength = 3 + (header.isBeginningSegment !== undefined ? 2 : 0);
will update that, thanks!

2023-07-10 19:51 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    isHandshakeRequest: false,
When we are sending a `handshake` response back, you can find it in `encodeBtpHandshakeResponse` inside `BtpCodec`

2023-07-10 19:55 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                }
the middle packets can never have `isEndingSegment` value as true, this will set `isEndingSegment` to true in case of middle packets which is incorrect.

2023-07-10 20:02 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private lastClientSequenceNumber = 255;
@Apollon77 do you think `prev` is the correct prefix for the variable since it checks for the last sequence number received by the client. wdyt?

2023-07-10 20:04 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (((this.lastClientSequenceNumber + 1) % 256) !== sequenceNumber) {
here, I am just checking if the incoming sequence number is an incremental of the previous one. I don't think updating the `getNextSequenceNumber` would help. Right @Apollon77 ?

2023-07-10 20:36 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            }
it is not an error, it just states that the window size is now full and we have to wait for the client to send in ack so that we can send new packets.

2023-07-10 20:38 UTC, Apollon77 requested changes

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
>      getNextSequenceNumber() {
I agree and also had that on my finalization list when functionality is ready ;-)

* yes methods should be private unless needed public. Your above list seems right. Rest should be private.
* async methods always return a promise and reject this when you throw. We favor to use async/await approach and not pure promises.
* Documentation is generated based on the typings. Als in general typescript should show all this magic in the IDE. Yes we can add that also as code, but formally it's not needed
* For error classes you are right, if we see it as a single reusable module ... Right now we honestly are mainly seeing is as "module used in scope of that package here" because it is (yes loosly coupled via the callbacks) but in the end very close to the matter library. We have dedicated errors for certain cases where we have want to detect that from outside. So here I would see a use for all "Closed because of sometging was invalid" cases as one errorclass. Other cases we need to see.

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
>              } = btpPacket;
@swan-amazon see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment?retiredLocale=de ... it's a language feature of JavaScript that you can work with normal variables and do not need to always access the object structure

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (!this.btpSendAckTimer.isRunning) {
maybe move down ... because not needed to be started when we end it afterwwards :-)

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                throw new Error("BTP packet must have a segment payload");
Thats right ... eighter remove the ble disconnection in the outer catch and add to all cases here or remove in the internal throw cases

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (hasAckNumber && ackNumber !== undefined) {
We try to only use null if it has a meaning. "undefined" is in fact the completely correct meaning here ... not present aka undefined.

In fact you are right and both is possible and there is no right or wrong. One of the devs that started this lib had the above opinion, so we try to stay that way.

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                this.currentSegmentedPayload = new ByteArray(); // resetting current segment Payload to empty byte array
No thats right.

* in the very first "btp segment message" we get told the length of the "full message" -> currentSegmentedMsgLength
* After this we get more packages with the payload and this is concat'ed into currentSegmentedPayload

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
>          const header = {
That format is defined in the Matter specs.

* payload is always binary data, in the end they are "matter message format"
* yes beginning (with message length), ending, both or neighter (for no payload or middle packets)
* no ack number can be there or not - depending on a header flag
* right now handshake req/response are the only ones with a opcode, all other packate do not have it

The data structure is modeled 1:1 after the message formats in the specs without extra fields.

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        let expectedBtpHeaderLength = 3 + (header.isBeginningSegment !== undefined ? 2 : 0);
right is always a boolean

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                }
No not the same ... would be with

```
isBeginningSegment: false, 
isEndingSegment: !isMiddlePacket,
```

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                }
Yes would be an idea, would then just need that helper variable defined outside of the loop. With the break we do not need that ...

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    async sendQueuesBtpFrames() {
We discused that. In fact the sending is a "big queue" and yes eg multiple matter messages could queue up to be sended. Also sending is async and can be needed to be paused because of the "receiving window" of the client could be reached then we need to wait for new packages coming in to resume sending.

Your proposal would potentially send out stuff in parallel which is not allowed. The incoming and outgoing side of BTP Session -> BLE messages is serial

We could have moved this into an own "Queue" class but becaus eof the client window considerations it is really about the "state of the btp session".

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            }
This is correct because we also need to consider the receiving window of the client as defined in Matter specs. See also above: in fact this is a queue ... and sending could be paused

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                    isHandshakeRequest: false,
only in hanshake requests or responses

2023-07-10 20:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            await this.writeBleCallback(packet);
We should vrify that the queue is not currently actively sending anything (esdge case) when queue sends too then we can handle it as ok here? Because it ould send ot that number ..... ?!

2023-07-10 20:53 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (((this.lastClientSequenceNumber + 1) % 256) !== sequenceNumber) {
The idea from @swan-amazon is to have a method which increases the number that you give in.
but that also means:

```
this.sequenceNumber = getNextSequenceNumber(this.getNextSequenceNumber);
```
And then use it. So method is no longer increasing the instance variable but "any" ...

Both valid approaches for me

2023-07-10 21:13 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            await this.writeBleCallback(packet);
in fact it should never happen that we send the queue and then this timer triggers because it should have been stopped ... so .. ok ignore . I close it

2023-07-10 21:22 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private lastClientSequenceNumber = 255;
prev is good

2023-07-10 21:29 UTC, kjwill2499 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private btpAckTimer: Timer; //
The btpAckTimer strategy seems like it has a gap. 

When you write you check if the timer is already running and start the timer if it is not running, and everytime you get an ack, you will stop the timer if the ackNumber is greater than the serverAckedSequenceNumber. If you had two writes but only got an ack back on the first one, you wouldn't have a timer running for the second write.

It seems like everytime you write you could restart the timer and then only stop timer when your serverAckedSequenceNumber has caught up to your sequenceNumber and that way you'd always have a timer running while waiting for an ack.

2023-07-10 21:40 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                expectedBtpHeaderLength = 2 + (this.serverAckedSequenceNumber !== undefined ? 1 : 0);
As discussed, updated it to 3

2023-07-10 21:47 UTC, kjwill2499 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                        this.serverAckedSequenceNumber = ackNumber;
Do we also have to restart timer if we are not at sequenceNumber?

2023-07-10 22:54 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                        this.serverAckedSequenceNumber = ackNumber;
yes, correct. Will be adding that logic soon.

2023-07-10 22:55 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private btpAckTimer: Timer; //
Still working on it! 
Will be there in the next commit. :)

2023-07-11 06:38 UTC, Apollon77 requested changes

2023-07-11 06:38 UTC, Apollon77 commented on packages/matter-node-ble.js/src/ble/BlenoBleServer.ts
> +        if (!this.btpHandshakeTimeout.isRunning) {
because only timer triggers it the timer is never running :-) you can remove this check

2023-07-11 06:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private btpPackets: Array<BtpPacket> = new Array<BtpPacket>();
nit: type is provide "twice" ... you can skip the first one because the "new Array..." is enough

2023-07-11 06:38 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            if (hasAckNumber && ackNumber !== undefined) {
PS: Alternative would be to have conditional types where the typing "knows" that "when hasAckFlag isset there also needs to be an ackNumber". having this would allow to only check for hasAckNumber and TS would know that ackNumber can not be undefined. Lets leave that for later :-)

2023-07-11 06:48 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private btpPackets: Array<BtpPacket> = new Array<BtpPacket>();
intelliJ is suggesting to replace it with `private btpPackets: Array<BtpPacket> = [];`

2023-07-11 07:10 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private btpPackets: Array<BtpPacket> = new Array<BtpPacket>();
lol ... so now IDEa have preferenes ... we use the above stated notation in most places ... in the end again_ both works fine for TS :-)

2023-07-11 21:25 UTC, kjwill2499 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +            }
I think you could reduce indentation and make this block a bit more readable by making validity checks at the top, doing the common logic, then resetting timer. Something like:

`if (hasAckNumber && ackNumber !== undefined) {
    // check that ack number is valid
    if (ackNumber < this.serverAckedSequenceNumber || ackNumber > this.sequenceNumber) {
        this.disconnectAndThrow(`Invalid Ack Number, Ack Number: ${ackNumber}, Sequence Number: ${this.sequenceNumber} Server Acked Sequence Number ${this.serverAckedSequenceNumber}`);
    }

    // for valid acks, stop timer and update serverAckedSequenceNumber
    this.ackReceiveTimer.stop();
    this.serverAckedSequenceNumber = ackNumber;

    // if still waiting for ack for sequence number restart timer
    if (ackNumber < this.sequenceNumber) {
        this.ackReceiveTimer.start();
    }
}`

2023-07-13 06:45 UTC, Apollon77 requested changes

2023-07-13 06:45 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +    private async sendQueuedBtpFrames(dataLength: number) {
Handling over the size of the "Latest added packet" makes no sense! see below

2023-07-13 06:45 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                isBeginningSegment: dataLength === remainingLengthInBytes,
sorry but noo ... with this you assume that the latest added packetis the obne you currently process which is an invalid assumption for a queue.
it is more this.queuesMatterMessages[0].length === remaininglengthInBytes .... buut the dataReader do not expose it's length right now ... so we would ideally enhance DataReader to aleo have a method to query the buffer length. 

Alternatively you remember that info in an instance variable like "currentMessageInFlightStarted" ... I think enhancement for DataReader is better

2023-07-13 06:45 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        this.queuesMatterMessages.shift();
here you always remove the first element - also if you would stop nbecause of client window size reached. this is wrong. only remove if packet is really done sending!

2023-07-13 06:45 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +        this.attMtu += 3;
this is wrong! because now your messages are 3 bytes to huge!

Maybe to stop confusion create a "this.fragmentSize = this.attMtu - 3" and us this is stead attMtu in all message lengt hcalculations below

2023-07-13 15:51 UTC, mahimamandhanaa commented on packages/matter.js/src/ble/BtpSessionHandler.ts
> +                isBeginningSegment: dataLength === remainingLengthInBytes,
Even I was kind of shaky about this logic, but yeah adding the method in DataReader makes more sense.

2023-07-19 07:43 UTC, merged

2023-07-19 07:44 UTC, Apollon77 commented
As talked I merged it, I will do some more preparations. Additional tests can please be done in a separate PR and we aff later. SO we can work on the topic in parallel

2023-07-19 08:52 UTC, Apollon77 commented on packages/matter.js/src/ble/BtpSessionHandler.ts
>              }
I will adjust it but I will not use a map ... irrelavtn performance wise for now